### PR TITLE
docs: Fix typos

### PR DESCRIPTION
**Pull request by etanot**
This merge request contains following changes:
  - Fix spell mistakes.
  - Add missing punctuations.
  - Fix whitespace errors.

### CODE REVIEW

**Review by tadzik — APPROVED** [review]
Good stuff – thanks a lot!

**Comment by etanot** [comment]
CI failed because of no changelog entry. @tadzik, do I need to add a changelog entry?

**Comment by jaller94** [comment]
@etanot Yes, as described here (linked in the CONTRIBUTING file of this repo).

https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#changelog

**Review by jaller94 — APPROVED** [review]
Sign-Offs are present on all commits. :+1:

**Pull request merged**
