### PR TITLE
Upgrade Dockerfile nodejs 12 => 14

### PR DESCRIPTION
**Pull request by 3nprob**
14 is the current LTS as per 2020-10

### CODE REVIEW

**Review by Half-Shot — COMMENTED** [review]
Seems like a reasonable change, can we have a changelog and signoff as per https://github.com/matrix-org/matrix-appservice-irc/blob/develop/CONTRIBUTING.md

**Comment by Half-Shot** [comment]
@3nprob ping?

**Comment by Half-Shot** [comment]
Sorry, we're going with #1299 because that has a changelog.

**Comment by 3nprob** [comment]
Ah sorrry missed the notification on this one @Half-Shot 

All good, progress is what matters, not whose pseudonym shows up in the commit log ;)

Thanks for maintaining!

**Pull request closed without merging**
