### PR TITLE
Add instructions for registering IRC bot's nickname

### PR DESCRIPTION
**Pull request by DylanVanAssche**
Setting up your own Matrix IRC bridge might require that you register the nickname of your IRC bot.
Some channels won't allow your bot to join without a registered nickname. As a result, the bot won't be able to join and cannot bridge the channel to Matrix.

This feature is already supported by the bridge, however it was not mentioned in the `HOWTO.md` guide for rolling your own bridge.

Signed-off-by: Dylan Van Assche <dylan.van.assche@protonmail.com>

### CODE REVIEW

**Comment by Half-Shot** [comment]
This seems good to me. Thanks :+1:

**Comment by Half-Shot** [comment]
Oh, almost! Can you base your changes against develop please?

**Comment by DylanVanAssche** [comment]
Changes based against `develop` :rocket:

**Comment by Half-Shot** [comment]
Oh and final final thing, as per https://github.com/matrix-org/matrix-appservice-irc/blob/master/CONTRIBUTING.md#making-pull-requests, could you add a changelog file so we can keep track of changes.

>Create a changelog entry in changelog.d. A changelog filename should be ${GithubIssueNumber}.{bugfix|misc|feature|doc|removal} The change should include information that is useful to the user rather than the developer.

Rememver to stick your github handle on the end of the changelog file to get credited :)

**Comment by DylanVanAssche** [comment]
I don't have a Github Issue, do I need one first? That's also the reason why I skipped the changelog thing when creating this PR

**Comment by Half-Shot** [comment]
Ah, the issue number is this PR's number (1004). Probably not clear enough in the docs.

**Comment by DylanVanAssche** [comment]
Done!

**Comment by DylanVanAssche** [comment]
Maybe describe in the guidelines the best 'template' for the changelog entries?

**Pull request merged**
