### PR TITLE
Add notice for unknown commands in the admin room

### LINKED ISSUE #570: admin room silently ignores invalid commands
which is terribly confusing

### PR DESCRIPTION
**Pull request by Half-Shot**
Fixes #570

### CODE REVIEW

**Comment by Half-Shot** [comment]
(Tests are failing due to some wonderful timeouts in the provisioner )

**Comment by Half-Shot** [comment]
I suggest this gets squshed :(, but otherwise it's ready to be poked at.

**Comment by lukebarnard1** [comment]
Looks like you need to merge `develop` into this.

**Comment by Half-Shot** [comment]
Done?

**Comment by lukebarnard1** [comment]
Nope, because e.g. 8eed0c3 is still on this branch as a change when it's unrelated.

**Comment by Half-Shot** [comment]
Seems happy now, sacrified some stuff to the git gods

**Pull request merged**
