### PR TITLE
Allow configuring channel keys for static mappings (with some changes to allow the existing format)

### PR DESCRIPTION
**Pull request by Half-Shot**
This adds some magic to use the existing format and the new format.

(Sorry @heftig, I can't append commits onto your PR)

### CODE REVIEW

**Comment by benparsons** [comment]
only thought: can we link to an anchor/title in the changelog

**Comment by heftig** [comment]
> I can't append commits onto your PR

Strange, because I do have "Allow edits from maintainers" enabled.

**Comment by Half-Shot** [comment]
> only thought: can we link to an anchor/title in the changelog

Not really, because the anchor have the dates of the releases in :(

**Comment by Half-Shot** [comment]
I might fix it before we release though.

**Pull request merged**
