### PR TITLE
Make sure a killed BridgedClient is dead, even if connect was never called

### LINKED ISSUE #944: unsafeClient not ready yet error
at LCA2020 we have a few people seeing this message when they try and connect to the bridge to freenode.

The bridge reports unsafeClient not ready yet 

this issue results in riot being able to join the irc channel and see what is happening on the channel but unable to send to the channel. when you send a message it appears to send correctly, but it never arrives in the irc channel, with no visible error message.

see attached screen shot

### PR DESCRIPTION
**Pull request by tilosp**
If for some reason `connect()` gets never called on a `BridgedClient` you will end up in a situation described in #944. The problem is that there is no way to solve this currently.
You can use the `!quit` command which calls `kill()` on `BridgedClient`, but that does not change the state of `isDead()`. This undying `BridgedClient` will remain around until the bridge gets restarted.

Fix #944

### CODE REVIEW

**Comment by Half-Shot** [comment]
This feels like the wrong solution to the problem :(. I feel like if we add yet-another-flag then it's going to get confusing between killed and dead. Perhaps a better solution would be an enum that tracks the state of the connection. E.g. "created", "connecting", "connected", "killed", "dead".

**Comment by tilosp** [comment]
@Half-Shot sure, i have a few questions regarding this enum:
- Should the connected checks, that are currently mostly based on null checking unsafeClient, be replaced with a check that state is `connected`?
- And is there any reason to have `killed` and `dead` as two different states?

**Comment by Half-Shot** [comment]
>Should the connected checks, that are currently mostly based on null checking unsafeClient, be replaced with a check that state is connected?

The null checking is mostly because it makes typescript happy, and allows us to catch the edge cases. I guess we should attempt to implement the enum as well as the type checking, if poss.

>And is there any reason to have killed and dead as two different states?

I would. `dead` can mean that the connection just died, `killed` is a explicit action from the user.

**Comment by tilosp** [comment]
@Half-Shot I have added the enum and replaced unsafeClient.

The ci doesn't seem to work on fork based PRs, but the tests seem to pass locally (at least the 198 that i was able to run).

**Comment by Half-Shot** [comment]
@tilosp I asked and got the CI working?

**Comment by tilosp** [comment]
> @tilosp I asked and got the CI working :)

thanks, and it's all green now :)

**Comment by djmitche** [comment]
This matches the circumstances I'm experiencing, which are preventing me from using the bridge.  I'd love to see that fixed!

**Comment by tilosp** [comment]
@Half-Shot could you take a another look at this?

**Comment by Half-Shot** [comment]
Will do, it's a little invasive so it may have to happen after this release now.

**Comment by tilosp** [comment]
Rebased onto master

**Comment by tilosp** [comment]
@Half-Shot is there any chance that this will ever get reviewed?
If not please tell me, so I don't waste any more time on solving merge conflicts.

**Comment by jaller94** [comment]
I cannot make any promises about the time this will take me to review but it's on the top of my list for community contributions.
ETA: Next week

The code looks good and we're in favour of the change, but I need to conduct some manual tests before it gets merged. :)

**Comment by Nuc1eoN** [comment]
Any news?

I would like to point out that without this PR, the IRC functionality is unfixably broken for many.
I don't understand how it does not have higher priority.

**Comment by tilosp** [comment]
Superseded by #1098

**Pull request closed without merging**
