### PR TITLE
Add strikethrough formatting

### PR DESCRIPTION
**Pull request by thomwiggers**

### CODE REVIEW

**Comment by tadzik** [comment]
With this applied, `ircToHtml()` works as well and I can see it working Hexchat -> Matrix:

```diff
diff --git a/src/irc/formatting.ts b/src/irc/formatting.ts
index 136b7f18..e3d4d2e6 100644
--- a/src/irc/formatting.ts
+++ b/src/irc/formatting.ts
@@ -262,13 +262,13 @@ export function ircToHtml(text: string): string {
     // Replace all mIRC formatting characters.
     // The color character can have arguments.
     // The regex matches:
-    // - Any single 'simple' formatting character: \x02, \x11, \x1d, \x1f, \x0f and
-    //   \x16 for bold, italics, underline, reset and reverse respectively.
+    // - Any single 'simple' formatting character: \x02, \x11, \x1d, \x1e, \x1f, \x0f and
+    //   \x16 for bold, italics, underline, strikethrough, reset and reverse respectively.
     // - The colour formatting character (\x03) followed by 0 to 2 digits for
     //   the foreground colour and (optionally) a comma and 1-2 digits for the
     //   background colour.
     // eslint-disable-next-line no-control-regex
-    const colorRegex = /[\x02\x11\x1d\x1f\x0f\x16]|\x03(\d{0,2})(?:,(\d{1,2}))?/g;
+    const colorRegex = /[\x02\x11\x1d\x1e\x1f\x0f\x16]|\x03(\d{0,2})(?:,(\d{1,2}))?/g;
 
     // Maintain a small state machine of which tags are open so we can close the right
     // ones on RESET codes and toggle appropriately if they do the same code again.
```

It doesn't seem to work for me from Matrix to Hexchat though; what did you test this on?

**Comment by thomwiggers** [comment]
The change seemed so simple that I hoped that the unit tests would be more than sufficient.

**Comment by tadzik** [comment]
Fixed it up in https://github.com/thomwiggers/matrix-appservice-irc/pull/1

**Comment by thomwiggers** [comment]
@tadzik thanks!

**Comment by tadzik** [comment]
Looks good, but we'll need a signoff and a changelog entry: see https://github.com/matrix-org/matrix-appservice-bridge/blob/develop/CONTRIBUTING.md#%EF%B8%8F-pull-requests

**Comment by thomwiggers** [comment]
I've rebased, squashed, signed off and fixed the name of the changelog file.

**Review by tadzik — APPROVED** [review]

**Comment by thomwiggers** [comment]
The failing changelog test seems due to a `.gitkeep` file in `changelog.d` that the tool is not set up to ignore.

**Comment by thomwiggers** [comment]
Rebased on #1813

**Pull request merged**
