### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by strugee**

### CODE REVIEW

**Comment by jaller94** [comment]
Hi @strugee, thanks for fixing this typo.
All matrix.org projects require a sign off, and I sadly don't know of an exception for small copy changes.

https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off

**Review by jaller94 — CHANGES_REQUESTED** [review]
Sign off seems to be missing.
I'll check with the team, if we can simplify this, by automating the request of a sign off and not requiring a sign off for minor contributions like typos.

**Comment by morguldir** [comment]
> Sign off seems to be missing.
> I'll check with the team, if we can simplify this, by automating the request of a sign off and not requiring a sign off for minor contributions like typos.

I recommend checking out https://github.blog/changelog/2022-06-08-admins-can-require-sign-off-on-web-based-commits/ as well (the commit was gpg signed by github, so it was web based)

**Comment by strugee** [comment]
Happy to sign DCO, just didn't know about it since I didn't see it in my quick scan of CONTRIBUTING.md - maybe link to https://github.com/matrix-org/matrix-appservice-bridge/blob/develop/CONTRIBUTING.md#%EF%B8%8F-pull-requests in the documentation section, since it's buried under "contributing code" which I dismissed as irrelevant? And it sounds like there are some other process improvements to be made here too.

In the meantime I'll push an amended patch with the signoff line!

**Comment by strugee** [comment]
Note that a typo fix like this is probably not even copyrightable.

**Comment by strugee** [comment]
Done!

**Comment by strugee** [comment]
Tests are failing due to lack of a changelog entry. Does this really need one or is the status check wrong?

**Comment by Half-Shot** [comment]
I don't think it's worth a changelog for this change :+1:

**Pull request merged**
