### PR TITLE
Comment out `tlsOptions` property in sample config

### LINKED ISSUE #1560: config: tlsOptions property fails schema validation
When attempting to generate a registration file, the config is validated against its schema. This fails for me because of the following error:

```
The field data.ircService.servers[keys2.0].tlsOptions is null which is the wrong type
/usr/lib/node_modules/matrix-appservice-irc/node_modules/matrix-appservice-bridge/lib/components/config-validator.js:77
            throw e;
            ^

Error: Failed to validate file
    at ConfigValidator.validate (/usr/lib/node_modules/matrix-appservice-irc/node_modules/matrix-appservice-bridge/lib/components/config-validator.js:75:23)
    at Cli.loadConfig (/usr/lib/node_modules/matrix-appservice-irc/node_modules/matrix-appservice-bridge/lib/components/cli.js:184:26)
    at Cli.assignConfigFile (/usr/lib/node_modules/matrix-appservice-irc/node_modules/matrix-appservice-bridge/lib/components/cli.js:164:29)
    at Cli.run (/usr/lib/node_modules/matrix-appservice-irc/node_modules/matrix-appservice-bridge/lib/components/cli.js:140:22)
    at Object.<anonymous> (/usr/lib/node_modules/matrix-appservice-irc/app.js:79:4)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module._load (node:internal/modules/cjs/loader:827:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  _validationErrors: [
    {
      field: 'data.ircService.servers[keys2.0].tlsOptions',
      message: 'is the wrong type',
      value: null,
      type: 'object',
      schemaPath: [
        'properties',
        'ircService',
        'properties',
        'servers',
        'additionalProperties',
        'properties',
        'tlsOptions'
      ]
    }
  ]
}

Node.js v18.0.0
```

The issue here is that `tlsOptions` isn't commented out by default, thus being present in the parent object and required to have an object as it's vaue by the schema. Commenting out `tlsOptions` fixes this issue.

### PR DESCRIPTION
**Pull request by jkhsjdhjs**
Fix #1560

### CODE REVIEW

**Review by tadzik — APPROVED** [review]

**Comment by tadzik** [comment]
Changelog is probably failing this: https://github.com/matrix-org/matrix-appservice-irc/blob/develop/scripts/check-newsfragment#L32

**Comment by jkhsjdhjs** [comment]
@tadzik Should be fine now

**Comment by jkhsjdhjs** [comment]
Looks like an issue with the CI check:
```
2024-08-01T12:26:57.7333573Z +++ [32mChecking newsfragment[m
2024-08-01T12:26:58.1581840Z Looking at these files:
2024-08-01T12:26:58.1582740Z ----
2024-08-01T12:26:58.1583756Z 1. /home/runner/work/matrix-appservice-irc/matrix-appservice-irc/changelog.d/1812.bugfix
2024-08-01T12:26:58.1585530Z 2. /home/runner/work/matrix-appservice-irc/matrix-appservice-irc/config.sample.yaml
2024-08-01T12:26:58.1586692Z Error: Invalid news fragment name: .gitkeep
2024-08-01T12:26:58.1588305Z If this filename is deliberate, add it to 'ignore' in your configuration.
2024-08-01T12:26:58.1592045Z ----
2024-08-01T12:26:58.1740080Z !! Please see the contributing guide for help writing your changelog entry:
2024-08-01T12:26:58.1742009Z https://github.com/matrix-org/matrix-appservice-irc/blob/develop/CONTRIBUTING.md#making-pull-requests
2024-08-01T12:26:58.1760343Z ##[error]Process completed with exit code 1.
```

**Comment by tadzik** [comment]
> Looks like an issue with the CI check:
> 
> ```
> 2024-08-01T12:26:57.7333573Z +++ �[32mChecking newsfragment�[m
> 2024-08-01T12:26:58.1581840Z Looking at these files:
> 2024-08-01T12:26:58.1582740Z ----
> 2024-08-01T12:26:58.1583756Z 1. /home/runner/work/matrix-appservice-irc/matrix-appservice-irc/changelog.d/1812.bugfix
> 2024-08-01T12:26:58.1585530Z 2. /home/runner/work/matrix-appservice-irc/matrix-appservice-irc/config.sample.yaml
> 2024-08-01T12:26:58.1586692Z Error: Invalid news fragment name: .gitkeep
> 2024-08-01T12:26:58.1588305Z If this filename is deliberate, add it to 'ignore' in your configuration.
> 2024-08-01T12:26:58.1592045Z ----
> 2024-08-01T12:26:58.1740080Z !! Please see the contributing guide for help writing your changelog entry:
> 2024-08-01T12:26:58.1742009Z https://github.com/matrix-org/matrix-appservice-irc/blob/develop/CONTRIBUTING.md#making-pull-requests
> 2024-08-01T12:26:58.1760343Z ##[error]Process completed with exit code 1.
> ```

Yep, should be good once https://github.com/matrix-org/matrix-appservice-irc/pull/1813 lands. Don't worry about it here, it's green to go as far as I'm concerned.

**Pull request merged**
