### PR TITLE
First naive Dockerfile for this bridge

### PR DESCRIPTION
**Pull request by kaiyou**
This PR provides a first implementation of a Dockerfile for this bridge. It is quite naive and should be improved upon, especially regarding the image layout and size; this probably needs a multi-stage build.

This is currently automatically built by the Docker Hub and available as ``tedomum/matrix-appservice-irc``.

### CODE REVIEW

**Comment by turt2live** [comment]
This does indeed look pretty good. I'm not too sure what the `ip route add` stuff actually gains us though.

The only other thing would be to add documentation to the README for using the thing (including generating the registration and starting it). Feel free to assume it'll exist on https://hub.docker.com/r/matrixdotorg/ - I'll try to convince anyone necessary to have it published there.

**Comment by kaiyou** [comment]
Sorry about the latest commits, I had forgotten my PR on the master branch. I'll close and recreate with a feature branch including some docs.

**Comment by t3chguy** [comment]
Follows pretty good docker intermediate image hygiene, could probably be further shrunk by making use of a build image and then just copying the build outputs across.

**Comment by kaiyou** [comment]
Closing here, since I opened #713.

**Pull request closed without merging**
