### PR TITLE
Allow configuring channel keys for static mappings

### PR DESCRIPTION
**Pull request by heftig**
In use by the archlinux.org bridge for quite some time now.

### CODE REVIEW

**Comment by Half-Shot** [comment]
Thanks for the PR.

Couple of things:

* When updating the config, please also update the schema and the sample config to match.
* I suspect it would be nice to keep mappings and keys inside the same object, is there no way we could reuse ``mappings`` for storing the keys.

**Comment by heftig** [comment]
>is there no way we could reuse mappings for storing the keys.

`mappings` is a `"#channel"`→ `"!roomid:matrix.org"` map so there's no way to add a channel key unless you propose somehow putting it into one of the strings, which would be weird.

**Comment by Half-Shot** [comment]
I'm proposing making ``mappings`` a key->object. ``"#channel" -> {roomid, key}``

**Comment by heftig** [comment]
@Half-Shot Is this better?

**Comment by Half-Shot** [comment]
Looks good, final thing is to add a changelog as per https://github.com/matrix-org/matrix-appservice-irc/blob/master/CONTRIBUTING.md#making-pull-requests. Ensure you highlight the change in schema prominently.

**Comment by heftig** [comment]
Is this supposed to be a one-liner or a multi-paragraph explanation?

**Comment by Half-Shot** [comment]
> Is this supposed to be a one-liner or a multi-paragraph explanation?

I recommend you put migration instructions for the config change into the changelog (probably a paragraph or so).

**Comment by heftig** [comment]
I added the following fragment:
<blockquote>

**Breaking Change** - Static mappings can now set a channel key:
 - This changes the config schema, even if you do not make use of this feature. You MUST update your existing `mappings` to use the new `roomIds`:
   ```yaml
   old:
     mappings:
       "#thepub": ["!kieouiJuedJoxtVdaG:localhost"]

   new:
     mappings:
       "#thepub":
         roomIds: ["!kieouiJuedJoxtVdaG:localhost"]
   ```
 - The key is automatically used to join Matrix users to the mapped channel. They do not need to know the key. For example, you can bridge password-protected IRC channels to invite-only Matrix rooms:
   ```yaml
   mappings:
     "#viplounge":
       roomIds: ["!xKtieojhareASOokdc:localhost"]
       key: "vip-pass"
   ```

</blockquote>

**Pull request merged**
