### PR TITLE
Correct validation of nicks

### PR DESCRIPTION
**Pull request by aidalgol**
Correct the regular expression for validating the starting character of a nick
to conform to RFC 2812 § 2.3.1.  It was considering only letters to be valid
starting characters, whereas the standard allows letters or special characters.

Fixes matrix-org/matrix-appservice-irc#467

### CODE REVIEW

**Comment by Half-Shot** [comment]
Hiya, thanks for contributing the PR :). Could you write an appropriate test file and case in https://github.com/matrix-org/matrix-appservice-irc/tree/master/spec/unit please just so we can make sure the behaviour is tested 👼

**Comment by aidalgol** [comment]
I studied the existing specs and started to write one for `BridgedClient` following their form, and I came up against the `BridgedClient` constructor requiring an `IrcServer`, an `IrcClientConfig`, an `IrcEventBroker`, an `IdentGenerator`, and an `Ipv6Generator`.  I see there is already an example of mocking `IrcClientConfig` in the `IdentGenerator` spec, but I'm having trouble figuring out what would be the bare minimum required for mocking the other classes.

**Comment by 0x4A6F** [comment]
@aidalgol, thanks for your work.
Any progress on this?

**Comment by aidalgol** [comment]
@0x4A6F No, I never got anywhere with writing tests for this.  Still keen to see this through, but I will need some guidance.

**Comment by dalcde** [comment]
Is this still being worked on? I would be happy to take it up. For the tests, it is probably easier to turn `getValidNick` into a static method, which it really ought to be imo, so that we don't have to construct a mock `BridgeClient` instance.

**Comment by Half-Shot** [comment]
@dalcde You're welcome to work on it, but since we moved to Typescript it might be better to start over.

**Comment by Half-Shot** [comment]
Thanks for kicking this change off @aidalgol. We've done the equivalent TS work in #1114 so closing this.

**Pull request closed without merging**
