### PR TITLE
Define power levels to disable calls/reactions/redaction/stickers in PMs initiated from IRC

### PR DESCRIPTION
**Pull request by progval**
No one but the sender can see them because we cannot bridge them. Blocking them with PLs allows the clients to hide these features from their UI, so users do not mistakenly believe they will be received.

### CODE REVIEW

**Comment by progval** [comment]
Signed-off-by: Valentin Lorentz <progval plus git at progval dot net>

**Comment by progval** [comment]
ping?

**Review by Half-Shot — CHANGES_REQUESTED** [review]
Looks fine, but needs to be targeting `develop`.

**Review by Half-Shot — APPROVED** [review]
Seems okay

**Pull request merged**
